FROM golang:1.22 as builder

WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the source code
# Adjust this line based on your project structure
COPY grpc_server/ ./



# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o grpc_server .
RUN ls -la /app/


FROM alpine:latest
WORKDIR /root/
# Copy the binary from the builder stage
COPY --from=builder /app/ .
# Expose the port the app runs on
EXPOSE 50051
# Run the binary
CMD ["./grpc_server"]